[package]
name = "yew-autocomplete"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "=0.2.83", features = ["serde-serialize"] }
yew = "0.19"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[[example]]
name = "autocomplete"
crate-type = ["cdylib"]